apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 349142834852.dkr.ecr.us-east-2.amazonaws.com/projector-backend
  newTag: ae60f301db66260c28df867e7fa9e95f984928da
- name: 349142834852.dkr.ecr.us-east-2.amazonaws.com/projector-frontend
  newTag: ae60f301db66260c28df867e7fa9e95f984928da
resources:
- resources/frontend.yaml
- resources/backend.yaml
- resources/ingress-service.yaml
- resources/mongo.yaml
- resources/ingress-controller.yaml
