version: '3'
services: 
    mongo:
        image: 'mongo'
        container_name: 'mongo-db'
        environment: 
            - MONGO_INITDB_DATABASE=projector-main
            - MONGO_INITDB_ROOT_USERNAME=projector-main-admin
            - MONGO_INITDB_ROOT_PASSWORD=projector-main-admin-secret-password
        volumes:
            - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
        ports:
            - 27017:27017

    frontend:
        build: ./frontend
        hostname: frontend
        ports:
            - 3000:3000
    backend:
        build: ./backend
        hostname: backend
        ports:
            - 8080:8080