version: '3'
services: 
    mongo:
        image: 'mongo'
        container_name: 'mongodb'
        # environment: 
        #     - MONGO_INITDB_DATABASE=projector-main
        #     - MONGO_INITDB_ROOT_USERNAME=projector-main-admin
        #     - MONGO_INITDB_ROOT_PASSWORD=projector-main-admin-secret-password
        #     - MONGO_INITDB_USERNAME=localuser
        #     - MONGO_INITDB_PASSWORD=localuser-password
        volumes:
            # - ./init-mongo:/docker-entrypoint-initdb.d/init-mongo.sh
            - ./mongo/data:/data/db
        ports:
            - 27017:27017
    # frontend:
    #     build: ./frontend
    #     hostname: frontend
    #     ports:
    #         - 3000:3000
    # backend:
    #     build: ./backend
    #     hostname: backend
    #     ports:
    #         - 8080:8080