name: 'Daikydesk - Deploy Backend'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checking out code
        uses: actions/checkout@v2
        with:
          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
          fetch-depth: 0

      - uses: nrwl/nx-set-shas@v2
      - run: npm ci
      - run: npx nx affected --target=build --parallel=3
      - name: 'Check file existence'
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: 'dist/apps/backend'

      - run: ls -la

  deploy:
    runs-on: ubuntu-latest
    environment: Production
    needs: [ build ]
    if: needs.deploy.check_files.outputs.files_exists == 'true'
    steps:
      - name: Logging into heroku
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          appdir: 'dist/apps/backend'
          justlogin: true
      - run: heroku git:remote -a "dailydesk"
      - run: git push --force heroku `git subtree split --prefix=dist/apps/backend HEAD`:refs/heads/main
